apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-task-tracker
  labels:
    app: devops-task-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-task-tracker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-task-tracker
    spec:
      containers:
        - name: devops-task-tracker
          image: ashleylobo2001/devops-task-tracker:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
