apiVersion: v1
kind: Service
metadata:
  name: devops-task-tracker-service
  labels:
    app: devops-task-tracker
spec:
  type: LoadBalancer
  selector:
    app: devops-task-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
